version: "3.3"

services:

  node:

    # コンテナ名を指定
    container_name: node

    # docker image を作成するときの指示をするファイル(Dockerfile)の場所を指定
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    
    # こうしておくことで後で3000ポートからアクセスすることが可能になる。
    ports:
      - 3000:3000
    # docker 内のディレクトリと同期させるディレクトリを指定。
    # ディレクトリが存在しない場合は勝手に作成される。
    volumes:
      - ./app/node:/app
    # tty: true とすることによりコンテナを継続させる。以下URLを参照。 
    # https://zenn.dev/hohner/articles/43a0da20181d34
    tty: true

  python:
    container_name: python
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    ports:
      - 5000:5000
    tty: true
    volumes: 
      - ./app/python/:/app
